-- =============================================================================
-- Master admin + OAuth (Google, GitHub, LinkedIn) — Supabase setup
-- Run selected statements in the Supabase SQL Editor as noted.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) Promote an existing user to platform admin (master login)
--
-- Create the account first: Authentication → Users → "Add user" (email/password)
-- or sign up through your app, then run (replace the email):
-- -----------------------------------------------------------------------------

-- update public.profiles
-- set role = 'admin'::user_role, updated_at = now()
-- where lower(email) = lower('admin@yourdomain.com');

-- -----------------------------------------------------------------------------
-- 2) If sign-up shows "Database error saving new user"
--
-- Run the full script in: supabase/fix-database-error-new-user.sql
-- (replaces handle_new_user + trigger with SECURITY DEFINER + search_path + owner)
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- 3) Dashboard checklist — Authentication → Providers
--
-- Google:   enable, set Web client ID + secret from Google Cloud Console
--           OAuth client: Authorized redirect URI = Supabase "Callback URL"
-- GitHub:   enable, create OAuth App on GitHub → paste Client ID + Secret
-- LinkedIn: enable "LinkedIn (OIDC)" — create LinkedIn app → Client ID + Secret
--
-- Authentication → URL configuration
--   Site URL:        https://www.thecallsheet.ai
--   Redirect URLs:   https://www.thecallsheet.ai/**
--                    https://www.thecallsheet.ai/update-password
--                    https://thecallsheet.ai/**          (apex redirects to www)
--                    http://localhost:5173/**
--                    http://localhost:5173/update-password
--
-- App env (Vercel): set VITE_PRODUCTION_URL = https://www.thecallsheet.ai on all environments
-- (preview auth/OAuth callbacks redirect to production, not the Vercel preview URL)
-- API check: curl https://www.thecallsheet.ai/api/health  (use www; apex returns 308 redirect)
-- -----------------------------------------------------------------------------
-- 4) Artist application workflow
--
-- Run: supabase/artist-applications.sql
-- Promote a user to admin to review applications (see section 1 above).
-- Share private invite links from /admin/invites (run supabase/artist-invites.sql first).
-- Artists apply at /apply?invite=TOKEN — the public /apply URL alone will not work.
-- -----------------------------------------------------------------------------
